/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import service.LogService;

public class Menu extends javax.swing.JFrame {
    public static String namaUser;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        URL iconURL = getClass().getResource("/images/icon.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        setTanggal();
//        updateTime();
        lNama.setText(namaUser);
        time();
        // Timer untuk mengupdate waktu setiap detik
//        Timer timer = new Timer(1000, new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                updateTime();
//            }
//        });
//        timer.start();
    }
    
    public void setTanggal() {
    java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd-MM-yyyy");
    lTgl.setText(kal.format(skrg));
    }
    
//    private void updateTime() {
//        // Format waktu
//        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
//        Date now = new Date();
//        String timeStr = sdf.format(now);
//
//        // Update label dengan waktu yang baru
//        lJam.setText(timeStr);
//    }
    
    private void time (){
        int i = 0;
        new Thread(){
            public void run(){
                while (i == 0){
                    Calendar kal = new GregorianCalendar();
                    int detik = kal.get(Calendar.SECOND);
                    int menit = kal.get(Calendar.MINUTE);
                    int jam = kal.get(Calendar.HOUR_OF_DAY);
                    lJam.setText(jam+":"+menit+":"+detik);
                }
            }
        }.start();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lJam = new javax.swing.JLabel();
        lTgl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        kelola = new javax.swing.JMenu();
        produk = new javax.swing.JMenuItem();
        pengguna = new javax.swing.JMenuItem();
        Log = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        penjualan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu - POS");
        setBackground(new java.awt.Color(180, 180, 230));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);
        setFont(new java.awt.Font("Californian FB", 0, 10)); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 530));

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 530));

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("   POS");
        jLabel1.setOpaque(true);

        lNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lNama.setText("--");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("User : ");

        lJam.setBackground(new java.awt.Color(0, 153, 255));
        lJam.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        lJam.setForeground(new java.awt.Color(255, 255, 255));
        lJam.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lJam.setText("JAM");
        lJam.setOpaque(true);

        lTgl.setBackground(new java.awt.Color(0, 153, 255));
        lTgl.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        lTgl.setForeground(new java.awt.Color(255, 255, 255));
        lTgl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lTgl.setText("TGL");
        lTgl.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(lTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNama))
                    .addComponent(lJam, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lJam, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNama)
                    .addComponent(jLabel4))
                .addContainerGap(350, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 1, 1, 1));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(300, 30));
        jMenuBar1.setVerifyInputWhenFocusTarget(false);

        kelola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document_files_icon.png"))); // NOI18N
        kelola.setText("Data");
        kelola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        produk.setText("Produk");
        produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkActionPerformed(evt);
            }
        });
        kelola.add(produk);

        pengguna.setText("Pengguna");
        pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penggunaActionPerformed(evt);
            }
        });
        kelola.add(pengguna);

        Log.setText("Log");
        Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogActionPerformed(evt);
            }
        });
        kelola.add(Log);

        jMenuBar1.add(kelola);

        transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart_shopping_icon.png"))); // NOI18N
        transaksi.setText("Transaksi");

        penjualan.setText("Penjualan");
        penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanActionPerformed(evt);
            }
        });
        transaksi.add(penjualan);

        jMenuBar1.add(transaksi);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users icon.png"))); // NOI18N
        jMenu3.setText("Opsi");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu3.add(logout);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jMenu3.add(keluar);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penggunaActionPerformed
        // TODO add your handling code here:
        new Pengguna().setVisible(true);
    }//GEN-LAST:event_penggunaActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        LogService.tambahLog("Logout", "User "+namaUser+" berhasil logout");
        this.dispose();
        lNama.setText("--");
    }//GEN-LAST:event_logoutActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkActionPerformed
        // TODO add your handling code here:
        new Produk().setVisible(true);
    }//GEN-LAST:event_produkActionPerformed

    private void penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanActionPerformed
        // TODO add your handling code here:
        new Transaksi().setVisible(true);
    }//GEN-LAST:event_penjualanActionPerformed

    private void LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogActionPerformed
        // TODO add your handling code here:
        new Log().setVisible(true);
    }//GEN-LAST:event_LogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
//        try {
//            UIManager.setLookAndFeel(new FlatMacLightLaf());
//            UIManager.put("Component.arrowType", "triangle");
//            UIManager.put("TitlePane.menuBarEmbedded", false);
//        } catch (UnsupportedLookAndFeelException ex){
//            System.err.println("Failed to initialize LaF");
//        }

//          try {
//              UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
//          } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
//              java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//          }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Log;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JMenu kelola;
    private javax.swing.JMenuItem keluar;
    private javax.swing.JLabel lJam;
    private static javax.swing.JLabel lNama;
    private javax.swing.JLabel lTgl;
    private static javax.swing.JMenuItem logout;
    private static javax.swing.JMenuItem pengguna;
    private javax.swing.JMenuItem penjualan;
    private javax.swing.JMenuItem produk;
    private static javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables
}
